# Generated by Django 3.1.5 on 2021-01-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=30, verbose_name='Temperatura')),
                ('date', models.CharField(max_length=30, verbose_name='Data')),
                ('time', models.CharField(max_length=30, verbose_name='Hora')),
                ('description', models.CharField(max_length=30, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'weather',
                'verbose_name_plural': 'weathers',
            },
        ),
    ]
